name: CI

on: [push]

jobs:
  editorconfig-checker:
    name: editorconfig-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  makrdown-lint:
    name: makdown-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx markdown-cli *.md

  extract-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Extract app version
        id: extract_version
        run: |
          app_version=$(grep '^version=' "./project.properties" | cut -d'=' -f2)
          echo "App Version: ${app_version}"
          echo "APP_VERSION=${app_version}" >> "$GITHUB_ENV"
      - name: Extract python version
        id: extract_python_version
        run: |
          python_version=$(grep '^python-version=' "./project.properties" | cut -d'=' -f2)
          echo "Python Version: ${python_version}"
          echo "PYTHON_VERSION=${python_version}" >> "$GITHUB_ENV"

  editorconfig:
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8" # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unittest:
    name: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
          architecture: x64
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Execute Unit Tests
        run: python3 -m unittest src/app_test.py

  # git-leaks:
  #   name: secrets detection
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 2
  #     - uses: gitleaks/gitleaks-action@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  database_test:
    needs: [ unittest, flake8, makrdown-lint, editorconfig-checker ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.16
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Run SQLite tests
        run: python3 -m unittest src/app_test.py

  sast:
    needs: [ database_test ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "SAST"
  sca:
    needs: [ database_test ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "SCA"