name: Main CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linting and Unit Tests
    uses: ./.github/workflows/lint.yml

  database_test:
    name: Database Testing
    uses: ./.github/workflows/database_test.yml
    needs: lint

  validate:
    name: Validation (Snyk & SonarCloud)
    uses: ./.github/workflows/validate.yml
    needs: database_test
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    name: Docker Build and Push
    uses: ./.github/workflows/docker.yml
    needs: validate
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
